# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Yazin Alirhayim
email: hi@yaz.in
description: > # this means to ignore newlines until "baseurl:"
  Muslim technology entrepeneur. Learn by doing.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yazin.org" # the base hostname & protocol for your site, e.g. http://example.com
enforce_ssl: yazin.org
twitter_username: yazinsai
github_username:  yazinsai
analytics: UA-89256258-1


# Custom stuff
permalink: /:categories/:title/
future: true # publish future posts too..

# Build settings
markdown: kramdown

theme: plain # custom theme (see https://github.com/yazinsai/jekyll-plain)
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-last-modified-at
keep_files:
  - assets/
exclude:
  - Gemfile
  - Gemfile.lock
defaults:
  -
    scope:
      path: "bookshelf"
      type: "posts"
    values:
      layout: bookshelf-book
      categories: bookshelf
